version: "3"
services: 
  springbootrbctask:
    container_name: stocksapi-rbctask
    image: stocksapi-rbctask-image
    restart: always
    build: .
    ports:
      - 8080:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: stocks
      MYSQL_ROOT_PASSWORD: root
